# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('content', tinymce.models.HTMLField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
