# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-27 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200527_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Article')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Person')),
            ],
        ),
    ]
