# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200529_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_id', models.IntegerField()),
                ('fan_id', models.IntegerField()),
            ],
        ),
    ]
