# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-30 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200529_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
