# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-14 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_recommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Person')),
            ],
        ),
        migrations.CreateModel(
            name='LikeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('fan_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MarkArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('fan_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recommend',
        ),
        migrations.RenameField(
            model_name='articlecomment',
            old_name='commenter',
            new_name='owner',
        ),
    ]
