# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-14 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200614_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_id', models.IntegerField()),
                ('fan_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MarkDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_id', models.IntegerField()),
                ('fan_id', models.IntegerField()),
            ],
        ),
    ]
