# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-14 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20200614_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDiscussionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.IntegerField()),
                ('fan_id', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
