# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-14 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_likediscussionresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likediscussionresponse',
            old_name='response_id',
            new_name='comment_id',
        ),
    ]
